# 特定のファイルタイプで読み込む
[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

# インサートモード時に読み込み
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

# unite
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

# unite.vim読み込み時
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

# denite
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'

# 特定のコマンド実行時
[[plugins]]
repo = 'thinca/vim-prettyprint'
on_cmd = ['PP', 'PrettyPrint']

# 特定のマッピング使ったら読み込む
# また、gvimでしか利用しない
[[plugins]]
repo = 'thinca/vim-fontzoom'
on_cmd = ['Fontzoom']
on_map = ['<Plug>(fontzoom-']
gui    = 1

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    if !exists('g:tcomment_types')
        let g:tcomment_types = {}
    endif
'''

[[plugins]]
repo = 'glidenote/memolist.vim'

# javascript
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'javascript.jsx']

[[plugin]]
repo = 'flowtype/vim-flow'
on_ft = ['javascript', 'javascript.jsx']

# MarkDownn用pulgin
# [[plugins]]
# # repo = 'rcmdnk/vim-markdown'
# repo = 'plasticboy/vim-markdown'
# [[plugins]]
# repo = 'kannokanno/previm'

# PlanUML用plugin
[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'kazuph/previm'
rev = 'feature/add-plantuml-plugin'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown']

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugin]]
repo = 'w0rp/ale'
